// Module: MOD-test-pages
// Level: release
// Guards: UC-013; UC-047; A PERSON IS TOLD WHAT WAITS FOR THEIR ACCEPTANCE; THE RELEASE TEST REPORT IS ACCEPTED BY A PERSON
import assert from "node:assert/strict";
import test from "node:test";
class E {constructor(){this.children=[];this.className="";this.listeners=new Map();this.value="";this.data={};}append(...x){this.children.push(...x);}replaceChildren(...x){this.children=x;}addEventListener(t,f){this.listeners.set(t,f);}async fire(t){await this.listeners.get(t)?.();}focus(){}get dataset(){return this.data;}get textContent(){return this.children.map(x=>x?.textContent??String(x)).join("");}set textContent(x){this.children=[String(x)];}}
globalThis.document={createElement:()=>new E()}; const {route}=await import("../src/test-pages/release.mjs"); const commit="a".repeat(40),tag="v2026.10.8-rc.1",job="docs/jobs/JOB-289.md"; const spec="# P\n\n**R** *(P)*\nRule.\n*Check:* `tests/x.mjs`\n",decl="// TST-X\n// level: unit\n// guards: R\n"; const record=["---","id: JOB-289","kind: run-tests","works_on:",`  - ${commit}`,"route: ci","started_by: p","start: x","agent_m: x","limit: 1","---","## Parameters","```json",JSON.stringify({candidate:{version:"2026.10.8",tag,commit},changelog:"entry"}),"```","## End","state: done"].join("\n"); const result=["---",`commit: ${commit}`,"levels:","  - unit","---","## Outcomes","| Test | Level | Outcome |","|---|---|---|", "| TST-X | unit | failed | |"].join("\n"); function snap(files,ref){return{repository:{path:"o/p"},ref,commit,paths:Object.keys(files),read:async p=>files[p]??null,blob:()=>"b".repeat(40)}} function els(n,c){const a=[];const w=x=>{for(const y of x.children??[]){if(y?.children){if(y.className?.split(" ").includes(c))a.push(y);w(y)}}};w(n);return a;}
function host({pending=true,complete=true,refuse=false}={}){const writes=[];return{writes,async repositoryInfo(){return{defaultBranch:"main"}},async listTags(){if(refuse)throw Error("refused");return pending?[{name:tag,commit}]:[]},async readSnapshot(ref){return snap(ref==="test-results"?(complete?{[`runs/${commit}/r.md`]:result}:{}):pending?{[job]:record,"SPEC.md":spec,"tests/x.mjs":decl}: {},ref)},async commitFiles(x){writes.push(x);return{commit}},async createTag(n,c){writes.push({n,c})}}}
// TST-289901
// level: release
// module: MOD-test-pages
// guards: UC-013; UC-047; A PERSON IS TOLD WHAT WAITS FOR THEIR ACCEPTANCE; THE RELEASE TEST REPORT IS ACCEPTED BY A PERSON
// given: a controlled repository host with a selected completed pending candidate, records, tag and failed test result
// input: public Release route opens, refreshes, supplies limitation/person, and explicitly accepts
// expect: opening/refreshing writes nothing; rendered report includes evidence/limitation; only acceptance writes matching report hash and tested tag, while refused/incomplete/no-pending paths are named without acceptance
test("TST-289901: public Release route reopens controlled pending report without opening writes",async()=>{const target=new E(),h=host();await route.render(target,{product:{host:h}},{});assert.match(target.textContent,/Release candidate/);assert.match(target.textContent,/TST-X/);assert.equal(h.writes.length,0);await els(target,"refresh")[0].fire("click");assert.equal(h.writes.length,0);const accept=els(target,"accept")[0];els(accept,"person")[0].value="akmaier";els(accept,"reason")[0].value="fixture limitation";await els(accept,"accept")[0].fire("click");assert.equal(h.writes.length,2);const no=new E();await route.render(no,{product:{host:host({pending:false})}},{});assert.match(no.textContent,/New release/);const incomplete=new E();await route.render(incomplete,{product:{host:host({complete:false})}},{});assert.match(incomplete.textContent,/not finished/i);assert.equal(els(incomplete,"accept").length,0);const refused=new E();await route.render(refused,{product:{host:host({refuse:true})}},{});assert.match(refused.textContent,/refused/i);});
