// Module: MOD-test-pages
// Level: release
// Guards: UC-013; UC-047; A PERSON IS TOLD WHAT WAITS FOR THEIR ACCEPTANCE; THE RELEASE TEST REPORT IS ACCEPTED BY A PERSON
import assert from "node:assert/strict";
import test from "node:test";
import { blobSha } from "../src/text-tools/index.mjs";
class E {constructor(){this.children=[];this.className="";this.listeners=new Map();this.value="";this.data={};this.innerHTML="";}append(...x){this.children.push(...x);}replaceChildren(...x){this.children=x;}addEventListener(t,f){this.listeners.set(t,f);}async fire(t){await this.listeners.get(t)?.();}focus(){}get dataset(){return this.data;}get textContent(){return this.children.map(x=>x?.textContent??String(x)).join("")+this.innerHTML;}set textContent(x){this.children=[String(x)];}}
globalThis.document={createElement:()=>new E()}; const {route}=await import("../src/test-pages/release.mjs"); const commit="a".repeat(40),tag="v2026.10.8-rc.1",job="docs/jobs/JOB-289.md"; const spec="# P\n\n**A SAMPLE REQUIREMENT** *(Product Owner)*\nA sample rule.\n*Check:* `tests/x.mjs`\n",decl="// TST-100\n// level: unit\n// module: MOD-test-pages\n// guards: A SAMPLE REQUIREMENT\n"; const record=["---","id: JOB-289","kind: run-tests","works_on:",`  - ${commit}`,"route: ci","started_by: p","start: x","agent_m: x","limit: 1","---","## Destinations","","## Parameters","","```json",JSON.stringify({candidate:{version:"2026.10.8",tag,commit},changelog:"entry"}),"```","","## End","","state: done"].join("\n"); const result=["---",`commit: ${commit}`,"levels:","  - unit","occasion: release-candidate","participant: ci","date: 2026-10-09 02:00 UTC","---","## Outcomes","","| Test | Level | Outcome | Runs |","|---|---|---|---|", "| TST-100 | unit | failed | |"].join("\n"); function snap(files,ref){return{repository:{path:"o/p"},ref,commit,paths:Object.keys(files),read:async p=>files[p]??null,blob:()=>"b".repeat(40)}} function els(n,c){const a=[];const w=x=>{for(const y of x.children??[]){if(y?.children){if(y.className?.split(" ").includes(c))a.push(y);w(y)}}};w(n);return a;}
function host({pending=true,complete=true,refuse=false}={}){const writes=[];return{writes,async repositoryInfo(){return{defaultBranch:"main"}},async listTags(){if(refuse)throw Error("refused");return pending?[{name:tag,commit}]:[]},async readSnapshot(ref){return snap(ref==="test-results"?(complete?{[`runs/${commit}/r.md`]:result}:{}):pending?{[job]:record,"SPEC.md":spec,"tests/x.mjs":decl}: {},ref)},async commitFiles(x){writes.push(x);return{commit}},async createTag(n,c){writes.push({n,c})}}}
// TST-289901
// level: release
// module: MOD-test-pages
// guards: UC-013; UC-047; A PERSON IS TOLD WHAT WAITS FOR THEIR ACCEPTANCE; THE RELEASE TEST REPORT IS ACCEPTED BY A PERSON
// given: a controlled repository host with a selected completed pending candidate, records, tag and failed test result
// input: public Release route opens, refreshes, supplies limitation/person, and explicitly accepts
// expect: opening/refreshing writes nothing; rendered report includes evidence/limitation; only acceptance writes matching report hash and tested tag, while refused/incomplete/no-pending paths are named without acceptance
test("TST-289901: public Release route reopens controlled pending report without opening writes",async()=>{const target=new E(),h=host();await route.render(target,{product:{host:h}},{});assert.match(target.textContent,/Release candidate/);assert.match(target.textContent,/TST-100/);assert.equal(h.writes.length,0);await els(target,"refresh")[0].fire("click");assert.equal(h.writes.length,0);const accept=els(target,"accept")[0];els(accept,"person")[0].value="akmaier";els(accept,"reason")[0].value="fixture limitation";await els(accept,"accept")[0].fire("click");assert.equal(h.writes.length,2);assert.equal(h.writes[1].n,"v2026.10.8");assert.equal(h.writes[1].c,commit);const files=h.writes[0].files;const report=files.find(file=>file.path==="docs/tests/releases/v2026.10.8.md");const approval=files.find(file=>file.path.startsWith("docs/approvals/release-v2026.10.8-"));const changelog=files.find(file=>file.path==="CHANGELOG.md");const blob=await blobSha(report.text);assert.match(approval.path,new RegExp(blob.slice(0,12)));assert.match(approval.text,/TST-100 — fixture limitation/);assert.match(changelog.text,/entry/);assert.match(report.text,/## Levels[\s\S]*unit/);assert.match(report.text,/## Tests[\s\S]*TST-100[\s\S]*failed/);assert.match(report.text,/## Requirements[\s\S]*A SAMPLE REQUIREMENT/);const unreasoned=host(),unreasonedTarget=new E();await route.render(unreasonedTarget,{product:{host:unreasoned}},{});const unreasonedAccept=els(unreasonedTarget,"accept")[0];els(unreasonedAccept,"person")[0].value="akmaier";await els(unreasonedAccept,"accept")[0].fire("click");assert.equal(unreasoned.writes.length,0);const no=new E();await route.render(no,{product:{host:host({pending:false})}},{});assert.match(no.textContent,/New release/);const incomplete=new E();await route.render(incomplete,{product:{host:host({complete:false})}},{});assert.match(incomplete.textContent,/not finished/i);assert.equal(els(incomplete,"accept").length,0);const refused=new E();await route.render(refused,{product:{host:host({refuse:true})}},{});assert.match(refused.textContent,/refused/i);});
